Major overhaul to link-pwd
No more .delete files.  Absence of .restore file is enough to figure out that if
there is a /target/ link, we delete it.

Made link and unlink and restore commands instead of a toggle with a file.

Added possiblity to put an array at the top of the script to use instead of the
linkfile so I can distribute the script to people.

diff --git a/bin/link-pwd b/bin/link-pwd
--- a/bin/link-pwd
+++ b/bin/link-pwd
@@ -1,44 +1,41 @@
 #!/bin/bash
 #
 cmd=$(basename $0)
+# linkfile=(" $HOME/.local/man/man1/link-pwd.1   man/man1/man_link-pwd.man" \
+# "$HOME/.local/man/man1/link-pwd.1   man/man1/man_link-pwd.man")
 ################################################################################
 # Save is either saving a copy of the link or remembering that there was nothing
 # there
 ################################################################################
-save_src(){
-    local src=$1
+save_target(){
+    local target=$1
 
-    if ! [ -e $src ] ; then
-        echo "$(tput setaf 5)REMEMBERING that there was no $src file by touching $(basename $src).delete$(tput sgr 0)"
-        touch $(basename $src).delete
-    else
-        echo "$(tput setaf 2)SAVING $src as $(basename $src).restore$(tput sgr 0)"
-        mv $src $(basename $src).restore
+    if [ -e $target ] ; then
+        echo "$(tput setaf 2)SAVING $target as $(basename $target).restore$(tput sgr 0)"
+        mv $target $(basename $target).restore
     fi
 }
+
 ################################################################################
 # Restore by either deleting or squashing with the saved file
 ################################################################################
-restore_src(){
-    local src=$1
-    local base_src=$(basename $src)
-    local restoration_file=$(find . -name "$base_src.restore" -o -name "$base_src.delete" | tail -1)
+restore_target(){
+    local target=$1
+    local base_target=$(basename $target)
+    local restore_file=$base_target.restore
 
-    if [ -z $restoration_file ] || ! [ -e $restoration_file ] ; then
-        return 0
-    fi
-
-    if [[ $restoration_file == *restore ]] ; then
-        echo "$(tput setaf 3)RESTORING $src from $restoration_file$(tput sgr 0)"
+    if [ -e $restore_file ] ; then
+        echo "$(tput setaf 3)RESTORING $target from $restore_file$(tput sgr 0)"
         # Note that the -T option doesn't work on OSX's mv command so I have to
-        # remove the link first otherwise, it might move $restoration_file
-        # into the directory pointed to by $src
-        rm -f $src
-        mv $restoration_file $src
-    elif [[ $restoration_file == *delete ]] && [ -L $src ] ; then
-        echo "$(tput setaf 1)DELETING link $src$(tput sgr 0)"
-        rm -f $src
-        rm $restoration_file
+        # remove the link first otherwise, it might move $restore_file
+        # into the directory pointed to by $target
+        rm -f $target
+        mv $restore_file $target
+    elif [ -L $target ] ; then
+        echo "$(tput setaf 1)DELETING link $target$(tput sgr 0)"
+        rm -f $target
+    elif [ -e $target ] ; then
+        echo "$(tput setaf 1)[[ CANT HAPPEN ]]Target $target exists and is not a link$(tput sgr 0)"
     fi
 }
 
@@ -55,51 +52,55 @@ maybe_link(){
     fi
 }
 
-unlink_src(){
-    local src=$1
+unlink_target(){
+    local target=$1
 
-    if [ -e $src ] && ! [ -L $src ] ; then
-        echo "$cmd : ERROR : unlink_src : src=$src exits and is not a link"
+    if [ -e $target ] && ! [ -L $target ] ; then
+        echo "$cmd : ERROR : unlink_target : target=$target exits and is not a link"
         exit 1
     fi
 
     if [ -e $target ] ; then
-        echo "$(tput setaf 1)DELETING link $src$(tput sgr 0)"
-        rm -f $src
+        echo "$(tput setaf 284)DELETING link $target$(tput sgr 0)"
+        rm -f $target
     fi
 }
 
 save_and_link(){
-    src=$1
-    my_file=$2
-    save_src $src $my_file
-    maybe_link $my_file $src
+    local target=$1
+    local my_file=$2
+    save_target $target $my_file
+    maybe_link $my_file $target
 }
 
 status()
 {
-    src=$1
-    my_file=$2
-    local base_src=$(basename $src)
-    local delete_file="$base_src.delete"
-    local restore_file="$base_src.restore"
-
-    if ! [ -z $delete_file ] && [ -e $delete_file ] ; then
-        echo "$(tput setaf 1)$delete_file : $(ls -s $src | tr -s ' ' | cut -d ' ' -f 9,10,11)$(tput sgr 0)"
-    fi
+    local target=$1
+    local my_file=$2
+    local base_target=$(basename $target)
+    local restore_file="$base_target.restore"
 
     if ! [ -z $restore_file ] && [ -e $restore_file ] ; then
-        echo "$(tput setaf 3)$(ls -l $restore_file | tr -s ' ' | cut -d ' ' -f 9,10,11)$(tput sgr 0)"
+        echo "$(tput setaf 3)Restore $(ls -l $restore_file | tr -s ' ' | cut -d ' ' -f 9,10,11)$(tput sgr 0)"
+    elif ! [ -e $restore_file ] && ! [ -e $target ]; then
+        echo "$(tput setaf 208)No Restore file for target $target.$(tput sgr 0)"
+    elif [ -L $target ] ; then
+        echo "$(tput setaf 208)Target $target exists but no Restore file.  Restore will delete it$(tput sgr 0)"
     fi
 
-    if [ -e $src ] && [ -L $src ] ; then
-        echo "$(tput setaf 4)$(ls -l $src | tr -s ' ' | cut -d ' ' -f 9,10,11)$(tput sgr 0)"
-    elif [ -e $src ] ; then
-        echo "$(tput setaf 1)$(ls -l $src | tr -s ' ' | cut -d ' ' -f 9,10,11)$(tput sgr 0)"
+    if [ -e $target ] && [ -L $target ] ; then
+        echo "$(tput setaf 4)Target $(ls -l $target | tr -s ' ' | cut -d ' ' -f 9,10,11)$(tput sgr 0)"
+    elif [ -e $target ] ; then
+        echo "$(tput setaf 1)Target $(ls -l $target | tr -s ' ' | cut -d ' ' -f 9,10,11) exists and is not a link$(tput sgr 0)"
+    else
+        echo "$(tput setaf 208)Target $target does not exist$(tput sgr 0)"
     fi
 
     if [ -e $my_file ] ; then
-        echo "$(tput setaf 2)$(ls -l $my_file | tr -s ' ' | cut -d ' ' -f 9,10,11)$(tput sgr 0)"
+        echo "$(tput setaf 2)My File : $(ls -l $my_file | tr -s ' ' | cut -d ' ' -f 9,10,11)$(tput sgr 0)"
+        true
+    else
+        echo "Myfile $my_file does not exist"
     fi
 }
 
@@ -119,9 +120,9 @@ if [[ "$1" != status ]] ; then
     i=1
     while read col1 extra ; do
         if [[ "$col1" != \#* ]] ; then
-            src=$(eval echo $col1)
-            if [ -e $src ] && ! [ -L $src ] ; then
-                echo "$cmd : ERROR : Linkfile line $i : src=$col1 exists and is not a link"
+            the_target=$(eval echo $col1)
+            if [ -e $the_target ] && ! [ -L $the_target ] ; then
+                echo "$cmd : ERROR : Linkfile line $i : the_target=$col1 exists and is not a link"
                 errors=true
             fi
         fi
@@ -133,37 +134,87 @@ if [[ "$1" != status ]] ; then
     fi
 fi
 
+
+error_restore(){
+    echo "$cmd : ERROR : Cannot $1 because there are restore files present"
+    echo "$cmd : ERROR : Check it out and run 'link-pwd forget' to clear restore files"
+}
+
+exists_restore_files()
+{
+    ls -a | grep '.\.restore' > /dev/null
+}
+
 ##################### Action based on presence of token file ###################
-if [[ "$1" == forget ]] ; then
-    rm -f ACTIVE
-    rm -f *.restore .*.restore
-    rm -f *.delete .*.delete
+case $1 in
+    forget)
+        rm -f *.restore .*.restore
+        exit 0
+        ;;
+    unlink)
+        if ! exists_restore_files ; then
+            action=save_target
+        else
+            error_restore $1
+            action=status
+            exit 1
+        fi
+        ;;
+    link)
+        if ! exists_restore_files ; then
+            action=save_and_link
+        else
+            error_restore $1
+            action=status
+            exit 1
+        fi
+        ;;
+    restore)
+        if exists_restore_files ; then
+            action=restore_target
+        else
+            echo "$cmd : No restore files present"
+            exit 1
+        fi
+        ;;
+    status)
+        action=status
+        ;;
+    *)
+        action=status
+        ;;
+esac
+
+if [ -e Linkfile ] ; then
+    ################# Iterateion on the lines of the file ##########################
+    while read column_1 column_2 extra ; do
+
+        if [[ "$column_1" = \#* ]] ; then
+            continue
+        fi
+
+        the_target=$(eval echo $column_1)
+        the_my_file=$this_dir/$(eval echo $column_2)
+
+        ! [ -z $action ] && $action $the_target $the_my_file
+
+    done < Linkfile
     exit 0
-elif [[ "$1" == unlink ]] ; then
-    action=save_src
-    touch ./ACTIVE
-elif [[ "$1" == status ]] ; then
-    action=status
-else
-    if [ -e ./ACTIVE ] ; then
-        action=restore_src
-        rm ./ACTIVE
+
+elif ! [ -z "$linkfile" ] ; then
+    exit 0
+    if [[ $this_dir == $PWD ]] ; then
+        for l in "${linkfile[@]}" ; do
+            the_target=$(echo $l | tr -s ' ' | cut -d ' ' -f 1)
+            the_my_file=$this_dir/$(echo $l | tr -s ' ' | cut -d ' ' -f 2)
+            ! [ -z $action ] && $action $the_target $the_my_file
+        done
     else
-        action=save_and_link
-        touch ./ACTIVE
+        echo "$0 : ERROR : The script needs to be called from the directory where it is to be used without a Linkfile"
+        exit 1
     fi
+else
+    echo "$cmd : ERROR :No links array in script and no Linkfile in pwd"
 fi
 
-################# Iterateion on the lines of the file ##########################
-while read column_1 column_2 extra ; do
 
-   if [[ "$column_1" = \#* ]] ; then
-      continue
-   fi
-
-   src=$(eval echo $column_1)
-   my_file=$this_dir/$(eval echo $column_2)
-
-   $action $src $my_file
-
-done < Linkfile
